### ISSUE TITLE
FA Image not mirrored correctly.

### ISSUE THREAD

**Issue by Shugabuga** [kupiakos/LapisMirror#32] opened 2016-09-01 15:33 UTC
[Example](https://www.reddit.com/r/zootopia/comments/50n4oe/good_morning_by_magenta7/d75c2kx)

I wonder if it's the fault of the source image, since Reddit also seems to struggle with the image preview, and my Reddit client (Alien Blue) did the same.

**Comment by kupiakos** [comment] 2016-09-01 16:48
Looks like a duplicate of #18.

**Closed as completed by kupiakos** 2016-09-01 16:48 UTC
